version: '3.8'

services:
  writer:
    build:
      context: .
      dockerfile: Dockerfile.writer
    ports:
      - "5003:5000"
    volumes:
      - shared_data:/shared

  reader:
    build:
      context: .
      dockerfile: Dockerfile.reader
    ports:
      - "5004:5001"
    volumes:
      - shared_data:/shared

volumes:
  shared_data:
